#version: "3.8"

services:
  kong-db:
    image: postgres:13
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    volumes:
      - kong-db-data:/var/lib/postgresql/data

  kong:
    image: kong:3.5
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-db
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - 8000:8000
      - 8001:8001
    depends_on:
      - kong-db

  test-service:
    build: ./services/test
    env_file: "./services/test/.env"
    ports:
      - "3000:3000"

  auth-service:
    build: ./services/auth
    env_file: "./services/auth/.env"
    ports:
      - "3001:3001"
    depends_on:
      - postgres-service

    # mongo:
    #   image: mongo:latest
    #   ports:
    #     - "27017:27017"

  postgres-service:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hospital
    ports:
      - "5432:5432"
    volumes:
      - ./databasepg:/var/lib/postgresql/data

volumes:
  kong-db-data:

networks:
  default:
    driver: bridge
