FROM python:3.9

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir fastapi uvicorn torch torchvision ultralytics opencv-python numpy pydicom Pillow

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8002"]
