FROM python:3.9-slim-buster

WORKDIR /app

COPY requirements.txt .

RUN apt-get update -y && \
    apt-get install -y --no-install-recommends libgl1-mesa-dev libglib2.0-0 && \
    pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir --upgrade -r requirements.txt && \
    rm -rf /var/lib/apt/lists/*

COPY . .

EXPOSE 3010

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "3010"]
